# site settings
title: Rust Faction Redux
subtitle: By old Rust Factions players, for new and old Rust Factions players
Discord: https://discord.gg/GtjpVbTbe9
description: Rust Factions brought back by original members from the .XYZ days with a clear focus on what made Rust Factions good! A clear RP focused sever with land claim, taxes and empire building features and minor PvP elements that exist solely to create a story for every player!
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Rad Road
city: Launch Site
state: Proc Gen
zip_code: 55555
country: Cobalt Minor Outlying Island
phone: (111) 222 3333

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Instagram:
  Discord: https://discord.gg/GtjpVbTbe9

  
# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
